"""
Temporary test for SQL self-correction.

This does NOT modify the production agent.
It verifies that sql_generator.py receives a previous SQL error
and attempts to generate a corrected query.
"""

from agent.sql_generator import generate_sql
from schema_catalog.expand_schema import load_schema_catalog, build_fk_graph
from schema_catalog.rank_schema_context import rank_schema_context
from schema_catalog.retrieve_schema import retrieve_schema


question = "Which customers rented the most movies?"

# Load the same schema and FK graph used by the real pipeline.
schema_catalog = load_schema_catalog()
fk_graph = build_fk_graph(schema_catalog)

# Retrieve and rank the schema context for the question.
retrieval_results = retrieve_schema(question, top_k=5)
ranked_context = rank_schema_context(retrieval_results, fk_graph)

# Simulate an execution error from a previous SQL attempt.
error_context = {
    "previous_sql": "SELECT bad_column FROM customer",
    "error_message": "Unknown column 'bad_column' in 'field list'",
}

# Ask the real SQL generator to correct the failed attempt.
result = generate_sql(
    question,
    ranked_context,
    error_context=error_context,
)

print("\nQuestion:")
print(question)

print("\nPrevious SQL:")
print(error_context["previous_sql"])

print("\nDatabase error:")
print(error_context["error_message"])

print("\nCorrected SQL generated by the model:")
print(result["sql"])